export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_AGE = 'CHANGE_AGE';
export const ADD_TWEET = 'ADD_TWEET';
export const REMOVE_TWEET = 'REMOVE_TWEET';
export const FETCH_TWEET_STARTED = 'FETCH_TWEET_STARTED';
export const FETCH_TWEET_SUCCESS = 'FETCH_TWEET_SUCCESS';
export const FETCH_TWEET_FAILED = 'FETCH_TWEET_FAILED';
export const UPDATE_TIME = 'UPDATE_TIME';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

