export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED';

export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILED = 'ADD_BOOK_FAILED';

export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILED = 'DELETE_BOOK_FAILED';

export const SEARCH_BOOK = 'SEARCH_BOOK';

export const VIEW_BOOK_DETAILS = 'VIEW_BOOK_DETAILS';
export const VIEW_BOOK_DETAILS_SUCCESS = 'VIEW_BOOK_DETAILS_SUCCESS';
export const VIEW_BOOK_DETAILS_FAILED = 'VIEW_BOOK_DETAILS_FAILED';

export const EDIT_BOOK_DETAILS = 'EDIT_BOOK_DETAILS';

export const API_URL = 'http://rest.learncode.academy/api/prakritisaxena/books';
